"""Notification system for watcher events.

Stores and manages notifications generated by the triage pipeline.
Supports in-memory and DB-backed implementations.
"""

from colloquip.notifications.store import (
    InMemoryNotificationStore,
    NotificationStore,
)

__all__ = [
    "NotificationStore",
    "InMemoryNotificationStore",
]
