"""Notification storage and management.

Stores notifications generated by the watcher triage pipeline.
Supports querying, filtering, and acting on notifications.
"""

import logging
from abc import ABC, abstractmethod
from datetime import datetime, timezone
from typing import Dict, List, Optional
from uuid import UUID

from colloquip.models import (
    Notification,
    NotificationAction,
    NotificationStatus,
)

logger = logging.getLogger(__name__)


class NotificationStore(ABC):
    """Abstract base for notification storage."""

    @abstractmethod
    async def save(self, notification: Notification) -> None:
        """Save a notification."""
        ...

    @abstractmethod
    async def get(self, notification_id: UUID) -> Optional[Notification]:
        """Get a notification by ID."""
        ...

    @abstractmethod
    async def list_by_subreddit(
        self,
        subreddit_id: UUID,
        status: Optional[NotificationStatus] = None,
        limit: int = 50,
    ) -> List[Notification]:
        """List notifications for a subreddit, optionally filtered by status."""
        ...

    @abstractmethod
    async def list_all(
        self,
        status: Optional[NotificationStatus] = None,
        limit: int = 50,
    ) -> List[Notification]:
        """List all notifications, optionally filtered by status."""
        ...

    @abstractmethod
    async def mark_read(self, notification_id: UUID) -> None:
        """Mark a notification as read."""
        ...

    @abstractmethod
    async def act(
        self,
        notification_id: UUID,
        action: NotificationAction,
        thread_id: Optional[UUID] = None,
    ) -> None:
        """Record an action taken on a notification.

        Raises ValueError if notification not found.
        """
        ...

    @abstractmethod
    async def count(
        self,
        subreddit_id: Optional[UUID] = None,
        status: Optional[NotificationStatus] = None,
    ) -> int:
        """Count notifications matching filters."""
        ...


class InMemoryNotificationStore(NotificationStore):
    """In-memory notification store for development and testing."""

    def __init__(self) -> None:
        self._notifications: List[Notification] = []
        self._by_id: Dict[UUID, Notification] = {}

    async def save(self, notification: Notification) -> None:
        if notification.id in self._by_id:
            self._notifications = [n for n in self._notifications if n.id != notification.id]
        self._notifications.append(notification)
        self._by_id[notification.id] = notification

    async def get(self, notification_id: UUID) -> Optional[Notification]:
        return self._by_id.get(notification_id)

    async def list_by_subreddit(
        self,
        subreddit_id: UUID,
        status: Optional[NotificationStatus] = None,
        limit: int = 50,
    ) -> List[Notification]:
        results = [n for n in self._notifications if n.subreddit_id == subreddit_id]
        if status is not None:
            results = [n for n in results if n.status == status]
        results.sort(key=lambda n: n.created_at, reverse=True)
        return results[:limit]

    async def list_all(
        self,
        status: Optional[NotificationStatus] = None,
        limit: int = 50,
    ) -> List[Notification]:
        results = list(self._notifications)
        if status is not None:
            results = [n for n in results if n.status == status]
        results.sort(key=lambda n: n.created_at, reverse=True)
        return results[:limit]

    async def mark_read(self, notification_id: UUID) -> None:
        notif = self._by_id.get(notification_id)
        if notif and notif.status == NotificationStatus.PENDING:
            notif.status = NotificationStatus.READ

    async def act(
        self,
        notification_id: UUID,
        action: NotificationAction,
        thread_id: Optional[UUID] = None,
    ) -> None:
        notif = self._by_id.get(notification_id)
        if notif is None:
            raise ValueError(f"Notification {notification_id} not found")

        notif.status = NotificationStatus.ACTED
        notif.action_taken = action
        notif.acted_at = datetime.now(timezone.utc)
        if thread_id:
            notif.thread_id = thread_id

    async def count(
        self,
        subreddit_id: Optional[UUID] = None,
        status: Optional[NotificationStatus] = None,
    ) -> int:
        results = self._notifications
        if subreddit_id is not None:
            results = [n for n in results if n.subreddit_id == subreddit_id]
        if status is not None:
            results = [n for n in results if n.status == status]
        return len(results)
