/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as MemoriesRouteImport } from './routes/memories'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AgentsIndexRouteImport } from './routes/agents/index'
import { Route as CNameRouteImport } from './routes/c/$name'
import { Route as AgentsAgentIdRouteImport } from './routes/agents/$agentId'
import { Route as CNameIndexRouteImport } from './routes/c/$name/index'
import { Route as CNameThreadThreadIdRouteImport } from './routes/c/$name/thread/$threadId'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const MemoriesRoute = MemoriesRouteImport.update({
  id: '/memories',
  path: '/memories',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsIndexRoute = AgentsIndexRouteImport.update({
  id: '/agents/',
  path: '/agents/',
  getParentRoute: () => rootRouteImport,
} as any)
const CNameRoute = CNameRouteImport.update({
  id: '/c/$name',
  path: '/c/$name',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsAgentIdRoute = AgentsAgentIdRouteImport.update({
  id: '/agents/$agentId',
  path: '/agents/$agentId',
  getParentRoute: () => rootRouteImport,
} as any)
const CNameIndexRoute = CNameIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CNameRoute,
} as any)
const CNameThreadThreadIdRoute = CNameThreadThreadIdRouteImport.update({
  id: '/thread/$threadId',
  path: '/thread/$threadId',
  getParentRoute: () => CNameRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/memories': typeof MemoriesRoute
  '/notifications': typeof NotificationsRoute
  '/settings': typeof SettingsRoute
  '/agents/$agentId': typeof AgentsAgentIdRoute
  '/c/$name': typeof CNameRouteWithChildren
  '/agents/': typeof AgentsIndexRoute
  '/c/$name/': typeof CNameIndexRoute
  '/c/$name/thread/$threadId': typeof CNameThreadThreadIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/memories': typeof MemoriesRoute
  '/notifications': typeof NotificationsRoute
  '/settings': typeof SettingsRoute
  '/agents/$agentId': typeof AgentsAgentIdRoute
  '/agents': typeof AgentsIndexRoute
  '/c/$name': typeof CNameIndexRoute
  '/c/$name/thread/$threadId': typeof CNameThreadThreadIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/memories': typeof MemoriesRoute
  '/notifications': typeof NotificationsRoute
  '/settings': typeof SettingsRoute
  '/agents/$agentId': typeof AgentsAgentIdRoute
  '/c/$name': typeof CNameRouteWithChildren
  '/agents/': typeof AgentsIndexRoute
  '/c/$name/': typeof CNameIndexRoute
  '/c/$name/thread/$threadId': typeof CNameThreadThreadIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/memories'
    | '/notifications'
    | '/settings'
    | '/agents/$agentId'
    | '/c/$name'
    | '/agents/'
    | '/c/$name/'
    | '/c/$name/thread/$threadId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/memories'
    | '/notifications'
    | '/settings'
    | '/agents/$agentId'
    | '/agents'
    | '/c/$name'
    | '/c/$name/thread/$threadId'
  id:
    | '__root__'
    | '/'
    | '/memories'
    | '/notifications'
    | '/settings'
    | '/agents/$agentId'
    | '/c/$name'
    | '/agents/'
    | '/c/$name/'
    | '/c/$name/thread/$threadId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MemoriesRoute: typeof MemoriesRoute
  NotificationsRoute: typeof NotificationsRoute
  SettingsRoute: typeof SettingsRoute
  AgentsAgentIdRoute: typeof AgentsAgentIdRoute
  CNameRoute: typeof CNameRouteWithChildren
  AgentsIndexRoute: typeof AgentsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memories': {
      id: '/memories'
      path: '/memories'
      fullPath: '/memories'
      preLoaderRoute: typeof MemoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/': {
      id: '/agents/'
      path: '/agents'
      fullPath: '/agents/'
      preLoaderRoute: typeof AgentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/$name': {
      id: '/c/$name'
      path: '/c/$name'
      fullPath: '/c/$name'
      preLoaderRoute: typeof CNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/$agentId': {
      id: '/agents/$agentId'
      path: '/agents/$agentId'
      fullPath: '/agents/$agentId'
      preLoaderRoute: typeof AgentsAgentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/$name/': {
      id: '/c/$name/'
      path: '/'
      fullPath: '/c/$name/'
      preLoaderRoute: typeof CNameIndexRouteImport
      parentRoute: typeof CNameRoute
    }
    '/c/$name/thread/$threadId': {
      id: '/c/$name/thread/$threadId'
      path: '/thread/$threadId'
      fullPath: '/c/$name/thread/$threadId'
      preLoaderRoute: typeof CNameThreadThreadIdRouteImport
      parentRoute: typeof CNameRoute
    }
  }
}

interface CNameRouteChildren {
  CNameIndexRoute: typeof CNameIndexRoute
  CNameThreadThreadIdRoute: typeof CNameThreadThreadIdRoute
}

const CNameRouteChildren: CNameRouteChildren = {
  CNameIndexRoute: CNameIndexRoute,
  CNameThreadThreadIdRoute: CNameThreadThreadIdRoute,
}

const CNameRouteWithChildren = CNameRoute._addFileChildren(CNameRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MemoriesRoute: MemoriesRoute,
  NotificationsRoute: NotificationsRoute,
  SettingsRoute: SettingsRoute,
  AgentsAgentIdRoute: AgentsAgentIdRoute,
  CNameRoute: CNameRouteWithChildren,
  AgentsIndexRoute: AgentsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
